[workspace]
members = ["crates/lib/*"]
resolver = "2"

[package]
name = "mountaineer"
# Bumped automatically by CI on a release
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
pyo3 = { version = "0.24.1", features = ["extension-module", "abi3-py310"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0"
path-absolutize = "3.1.1"
regex = "1.11.1"
toml = "0.8"
mountaineer-file-monitor = { path = "crates/lib/file-monitor" }
mountaineer-vite = { path = "crates/lib/vite" }
mountaineer-hot-reload-discover = { path = "crates/lib/hot-reload-discover" }
mountaineer-ssr = { path = "crates/lib/ssr" }
mountaineer-terminal = { path = "crates/lib/terminal" }

log = "0.4"
env_logger = "0.11"
console = "0.16"
indicatif = "0.18"

tokio = { version = "1.43.0", features = ["full"] }

tempfile = "3.16.0"
clap = { version = "4.6.4", features = ["derive"] }

[target.'cfg(unix)'.dependencies]
mountaineer-hot-reload-fork = { path = "crates/lib/hot-reload-fork" }

[target.'cfg(windows)'.dependencies]
mountaineer-hot-reload-pool = { path = "crates/lib/hot-reload-pool" }


[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[profile.release]
opt-level = 3
debug = false
lto = true
incremental = false

[package.metadata.maturin]
name = "mountaineer"

[[bench]]
path = "src/benches/source_map_benchmark.rs"
name = "source_map_benchmark"
harness = false

[[bench]]
path = "src/benches/ssr_benchmark.rs"
name = "ssr_benchmark"
harness = false

[[bench]]
path = "src/benches/lexers_benchmark.rs"
name = "lexers_benchmark"
harness = false

[lints.rust]
# Global allow to fix pymethods's macro expansion, which can't be
# escaped with an inline #[allow]
non_local_definitions = "allow"
