[package]
name = "mountaineer-ssr"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
console = "0.16"
deno_core_icudata = "0.73.0"
log = "0.4"
mountaineer-terminal = { path = "../terminal" }
v8 = "129.0.0"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["processthreadsapi"] }
