mod actions;
mod controllers;
mod links;
mod schema;
mod support;
mod use_server;

use self::{
    actions::local_actions,
    controllers::{global_controllers, local_models},
    links::{global_links, local_links},
    use_server::local_use_server,
};
use super::{manifest::Envelope, output::OutputPlan, Result};
use std::collections::HashMap;

pub(super) fn render(envelope: &Envelope) -> Result<OutputPlan> {
    let mut output = OutputPlan::default();
    output.write(
        envelope.global_root.join("api.ts"),
        include_str!("../../../mountaineer/static/api.ts"),
    )?;
    output.write(
        envelope.global_root.join("live_reload.ts"),
        include_str!("../../../mountaineer/static/live_reload.ts"),
    )?;

    let components: HashMap<_, _> = envelope
        .components
        .iter()
        .map(|component| (component.global_name.as_str(), component))
        .collect();
    let controllers: HashMap<_, _> = envelope
        .controllers
        .iter()
        .map(|controller| (controller.global_name.as_str(), controller))
        .collect();

    output.write(
        envelope.global_root.join("controllers.ts"),
        generated(&envelope.mountaineer_version, global_controllers(envelope)),
    )?;
    output.write(
        envelope.global_root.join("links.ts"),
        generated(&envelope.mountaineer_version, global_links(envelope)?),
    )?;
    output.write(
        envelope.global_root.join("index.ts"),
        generated(
            &envelope.mountaineer_version,
            vec![
                "export * from './api';\nexport * from './controllers';\nexport * from './links';"
                    .into(),
            ],
        ),
    )?;

    for view in &envelope.views {
        let actions = view.managed_dir.join("actions.ts");
        let models = view.managed_dir.join("models.ts");
        let use_server = view.managed_dir.join("useServer.ts");

        output.write(
            &actions,
            generated(
                &envelope.mountaineer_version,
                local_actions(view, &envelope.global_root, &components)?,
            ),
        )?;
        output.write(
            &models,
            generated(
                &envelope.mountaineer_version,
                local_models(view, &envelope.global_root, &components, &controllers)?,
            ),
        )?;
        output.write(
            &use_server,
            generated(
                &envelope.mountaineer_version,
                local_use_server(view, &envelope.global_root)?,
            ),
        )?;

        let mut modules = vec!["actions", "models", "useServer"];
        let links = view.managed_dir.join("links.ts");
        if view.is_layout {
            output.remove(links)?;
        } else {
            output.write(
                &links,
                generated(
                    &envelope.mountaineer_version,
                    local_links(view, &envelope.global_root)?,
                ),
            )?;
            modules.insert(1, "links");
        }
        output.write(
            view.managed_dir.join("index.ts"),
            generated(
                &envelope.mountaineer_version,
                vec![modules
                    .into_iter()
                    .map(|module| format!("export * from './{module}';"))
                    .collect::<Vec<_>>()
                    .join("\n")],
            ),
        )?;
    }

    Ok(output)
}

fn generated(version: &str, blocks: Vec<String>) -> String {
    let body = blocks
        .into_iter()
        .filter(|block| !block.trim().is_empty())
        .collect::<Vec<_>>()
        .join("\n\n");
    format!(
        "/*\n * This file was generated by Mountaineer v{version}. Do not edit it manually.\n */\n\n{body}"
    )
}
